language: php

sudo: false

git:
    depth: 1

matrix:
    fast_finish: true
    include:
        - php: 5.5.9
        - php: 5.6
        - php: 7.0
          env: deps=high
        - php: 7.1
          env: deps=low
        - php: nightly
          dist: trusty
          group: edge
        - php: hhvm
          sudo: required
          dist: trusty
          group: edge
        - php: hhvm-3.12
          sudo: required
          dist: trusty
          group: edge
    allow_failures:
        - php: nightly

install:
    - travis_retry composer install --no-interaction --prefer-source

before_script:
    - PHP=$TRAVIS_PHP_VERSION;
    - INI_FILE=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini;
    - if [[ $PHP = 5.5.9 ]]; then yes "" | pecl install -f memcached-2.1.0; fi
    - if [[ $PHP = 5.6 ]]; then yes "" | pecl install -f memcached-2.2.0; fi
    - if [[ ! $PHP = hhvm* ]]; then echo "extension = memcached.so" >> INI_FILE; fi
    - php -r "echo 'Memcached @ [' . phpversion('memcached') . \"]\n\";"
script:
    - phpunit --verbose
