language: php

sudo: false

git:
    depth: 1

matrix:
    fast_finish: true
    include:
        - php: 5.5.9
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
        - php: 5.6
          env: COMPOSER_FLAGS="--prefer-stable"
        - php: 7.0
          env: COMPOSER_FLAGS="--prefer-stable"
        - php: 7.1
          env: COMPOSER_FLAGS="--dev"
        - php: hhvm-3.9
          sudo: required
          dist: trusty
          group: edge
          env: COMPOSER_FLAGS="--prefer-stable"
        - php: hhvm-nightly
          sudo: required
          dist: trusty
          group: edge
          env: COMPOSER_FLAGS="--dev"
    allow_failures:
        - php: hhvm-nightly

install:
    - composer update $COMPOSER_FLAGS --no-interaction -v
    - if [[ $TRAVIS_PHP_VERSION = 7.0 ]]; then curl -L https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v2.0.0/php-cs-fixer.phar -o php-cs-fixer.phar; fi

before_script:
    - PHP=$TRAVIS_PHP_VERSION;
    - INI_FILE=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini;
    - if [[ $PHP = 5.5.9 ]]; then yes "" | pecl install -f memcached-2.1.0; fi
    - if [[ $PHP = 5.6 ]]; then yes "" | pecl install -f memcached-2.2.0; fi
    - if [[ ! $PHP = hhvm* ]]; then echo "extension = memcached.so" >> INI_FILE; fi
    - php -r "echo 'Memcached @ [' . phpversion('memcached') . \"]\n\";"

script:
    - phpunit --verbose
    - if [[ $TRAVIS_PHP_VERSION = 7.0 ]]; then php php-cs-fixer.phar --dry-run -vvv fix; fi
