sudo: required

language: php

php:
  - 5.6

services:
  - memcached

# The `sevices: memcache` will start a memcached service on localhost and on the default port,
# but in order to test against multiple memcached instances we need to spawn a couple more,
# so we do that during the before script
before_script:
  - memcached -p 11212 -d
  - memcached -p 11213 -d
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - php -i | grep memcached
  - echo stats | nc 127.0.0.1 11211

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - phpunit --verbose
